msgid ""
msgstr ""
"Project-Id-Version: src_debug_tserver\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-05-13 12:03+EDT\n"
"PO-Revision-Date: 2018-03-18 22:27+0300\n"
"Last-Translator: alexandr\n"
"Language-Team: Russian\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10 >= 2 && n"
"%10<=4 &&(n%100<10||n%100 >= 20)? 1 : 2);\n"
"X-Generator: Loco https://localise.biz\n"
"X-Loco-Source-Locale: en\n"
"X-Loco-Project-Id: 44387\n"
"X-Loco-Api-Version: 1.0.19 20180317-1\n"

#: src/debug/tserver/abstract.py:346
msgid "Wing Debug Log File\n"
msgstr "Файл журнала отладки Wing"

#: src/debug/tserver/abstract.py:347
msgid "This file can be used to diagnose problems in debugger internals\n"
msgstr ""
"Этот файл можно использовать для диагностики проблем во внутренних "
"компонентах отладчика"

#: src/debug/tserver/abstract.py:348
msgid "For help, contact support@wingware.com\n"
msgstr "За помощью обращайтесь по адресу support@wingware.com"

#: src/debug/tserver/abstract.py:353
msgid "Warning:  Log file does not exist:\n"
msgstr "Предупреждение: файл журнала не существует:"

#: src/debug/tserver/abstract.py:355
msgid "Warning:  and could not be created; logging disabled\n"
msgstr "Предупреждение: и не удалось создать; ведение журнала отключено"

#: src/debug/tserver/abstract.py:358
msgid "Warning:  Log file is not a file:\n"
msgstr "Предупреждение: файл журнала не является файлом:"

#: src/debug/tserver/abstract.py:360
msgid "Warning:  Logging disabled\n"
msgstr "Предупреждение: ведение журнала отключено"

#: src/debug/tserver/dbginspect.py:58 src/debug/tserver/dbgserver.py:3060
#: src/debug/tserver/dbgutils.py:489 src/debug/tserver/dbgutils.py:510
msgid "(truncated)"
msgstr ""

#: src/debug/tserver/dbginspect.py:929 src/debug/tserver/dbgutils.py:499
#: src/debug/tserver/dbgutils.py:520 src/debug/tserver/dbgutils.py:3156
msgid "<opaque "
msgstr "<непрозрачный "

#: src/debug/tserver/dbgserver.py:1291
msgid "<module>"
msgstr "<модуль>"

#: src/debug/tserver/dbgserver.py:1433
msgid "<error evaluating>"
msgstr "<оценка ошибок>"

#: src/debug/tserver/dbgserver.py:2029 src/debug/tserver/dbgserver.py:2065
msgid "<thread %i is running>"
msgstr "<поток %i запущен>"

#: src/debug/tserver/dbgserver.py:2032 src/debug/tserver/dbgserver.py:2068
msgid "<invalid thread id %s or stack index %s>"
msgstr "<Неверный поток id %s или указатель стека  %s>"

#: src/debug/tserver/dbgserver.py:2034 src/debug/tserver/dbgserver.py:2070
msgid "<invalid stack frame>"
msgstr "<недопустимый фрейм стека>"

#: src/debug/tserver/dbgserver.py:2098 src/debug/tserver/dbgserver.py:2127
msgid "<sys.modules does not exist>"
msgstr "<sys.modules не существует>"

#: src/debug/tserver/dbgserver.py:2101 src/debug/tserver/dbgserver.py:2132
msgid "<error accessing sys.modules>"
msgstr "<ошибка доступа sys.modules>"

#: src/debug/tserver/dbgserver.py:2129
msgid "<no longer exists"
msgstr "<больше не существует"

#: src/debug/tserver/dbgserver.py:2177 src/debug/tserver/dbgserver.py:2230
msgid "<no longer exists>"
msgstr "<более не существует>"

#: src/debug/tserver/dbgserver.py:2208 src/debug/tserver/dbgserver.py:4518
msgid "<parent too large>"
msgstr "<слишком большое значение родителя>"

#: src/debug/tserver/dbgserver.py:2210 src/debug/tserver/dbgserver.py:4520
msgid "<invalid parent type>"
msgstr "<неверный тип родителя>"

#: src/debug/tserver/dbgserver.py:2220 src/debug/tserver/dbgserver.py:2689
msgid "<value not found>"
msgstr "<значение не найдено>"

#: src/debug/tserver/dbgserver.py:2677
msgid "<thread is running>"
msgstr "<поток запущен>"

#: src/debug/tserver/dbgserver.py:2679
msgid "<invalid context>"
msgstr "<недопустимый контекст>"

#: src/debug/tserver/dbgserver.py:4526
msgid "<invalid path %s at pos=%i>"
msgstr "<неверный путь %s в pos=%i>"

#: src/debug/tserver/dbgutils.py:151
msgid "<undefined>"
msgstr ""

#: src/debug/tserver/dbgutils.py:167
msgid "at"
msgstr ""

#: src/debug/tserver/dbgutils.py:177
msgid "len=%s>"
msgstr ""

#: src/debug/tserver/dbgutils.py:187 src/debug/tserver/dbgutils.py:2649
#, fuzzy
msgid "<error handling value>"
msgstr "<оценка ошибок>"

#: src/debug/tserver/dbgutils.py:189
msgid "<timeout>"
msgstr ""

#: src/debug/tserver/dbgutils.py:197
msgid "<huge "
msgstr ""

#: src/debug/tserver/dbgutils.py:217
msgid "<long "
msgstr ""

#: src/debug/tserver/dbgutils.py:234
#, fuzzy
msgid "<opaque"
msgstr "<непрозрачный "

#: src/debug/tserver/dbgutils.py:512
msgid "<huge %s at %s; len=%i>"
msgstr "<очень большой %s в %s; len=%i>"

#: src/debug/tserver/dbgutils.py:726 src/debug/tserver/dbgutils.py:738
msgid ", pos "
msgstr ", поз "

#: src/debug/tserver/dbgutils.py:742
msgid ", line "
msgstr ", строка "

#: src/debug/tserver/dbgutils.py:744
msgid "SyntaxError: "
msgstr "Ошибка синтаксиса: "

#: src/debug/tserver/dbgutils.py:772
msgid "Error"
msgstr "Ошибка"

#: src/debug/tserver/dbgutils.py:782
msgid "Error: Wing was unable to pack up an exception message"
msgstr "Ошибка: Wing не смог собрать сообщение об исключении"

#: src/debug/tserver/dbgutils.py:3518 src/debug/tserver/dbgutils.py:3534
msgid "Key"
msgstr ""

#: src/debug/tserver/dbgutils.py:3518 src/debug/tserver/dbgutils.py:3534
msgid "Value"
msgstr ""

#: src/debug/tserver/dbgutils.py:3529 src/debug/tserver/dbgutils.py:3556
msgid "Item"
msgstr ""

#: src/debug/tserver/netserver.py:472
msgid "Redirected I/O failed on closed debug connection"
msgstr "Сбой перенаправленного ввода-вывода при закрытом отладочном соединении"

#: src/debug/tserver/netserver.py:635
msgid "EOF when reading a line"
msgstr "EOF при чтении строки"

#: src/debug/tserver/netserver.py:1209
msgid "(unavailable)"
msgstr "(недоступен)"

#: src/debug/tserver/netserver.py:1472
msgid "[omitting some output]"
msgstr "[опуская некоторый вывод]"

#: src/debug/tserver/startdebug.py:205 src/debug/tserver/startdebug.py:390
#, fuzzy
msgid "wingdb.py: Error: Debug file does not exist:"
msgstr "Предупреждение: файл журнала не существует:"

#: src/debug/tserver/startdebug.py:209 src/debug/tserver/startdebug.py:394
#, fuzzy
msgid "wingdb.py: Error: Debug file is not a file:"
msgstr "Предупреждение: файл журнала не является файлом:"

#: src/debug/tserver/startdebug.py:443
msgid "Network peer is "
msgstr ""

#: src/debug/tserver/startdebug.py:444
msgid "Attach port = "
msgstr ""

#: src/debug/tserver/startdebug.py:445
msgid "Initial stop = "
msgstr ""

#: src/debug/tserver/startdebug.py:459
msgid "wingdb.py: Could not create debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:481
msgid "wingdb.py: Running %s"
msgstr ""

#: src/debug/tserver/startdebug.py:492 src/debug/tserver/startdebug.py:519
msgid "wingdb.py: Server exiting abnormally on exception"
msgstr ""

#: src/debug/tserver/startdebug.py:681
msgid "wingdb.py: Error: Failed to start the debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:682
msgid "wingdb.py: Error: You may be running an unsupported version of Python"
msgstr ""

#: src/debug/tserver/startdebug.py:683
msgid "wingdb.py: Python version = %s"
msgstr ""

#: src/debug/tserver/startdebug.py:768 src/debug/tserver/startdebug.py:770
msgid "-- Type return or enter to exit --\n"
msgstr ""
